### ISSUE TITLE
MAC - mamba error

### ISSUE THREAD

**Issue by skanwal** [umccr/cwl-novice-tutorial#6]
```
 $ mamba install cwltool graphviz wget git nodejs
Traceback (most recent call last):
  File "/Users/kanwals/miniconda/envs/cwltutorial/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/Users/kanwals/miniconda/envs/cwltutorial/lib/python3.11/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/Users/kanwals/miniconda/envs/cwltutorial/lib/python3.11/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/Users/kanwals/miniconda/envs/cwltutorial/lib/python3.11/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Users/kanwals/miniconda/envs/cwltutorial/lib/python3.11/site-packages/libmambapy/bindings.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libarchive.13.dylib
  Referenced from: <93863E94-4249-375D-BA9E-AF3A463FD1A0> /Users/kanwals/miniconda/envs/cwltutorial/lib/libmamba.2.0.0.dylib
  Reason: tried: '/Users/kanwals/miniconda/envs/cwltutorial/lib/libarchive.13.dylib' (no such file), '/Users/kanwals/miniconda/envs/cwltutorial/lib/python3.11/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/Users/kanwals/miniconda/envs/cwltutorial/lib/python3.11/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/Users/kanwals/miniconda/envs/cwltutorial/bin/../lib/libarchive.13.dylib' (no such file), '/Users/kanwals/miniconda/envs/cwltutorial/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/lib/libarchive.13.dylib' (no such file), '/usr/lib/libarchive.13.dylib' (no such file, not in dyld cache)
```

Tried downgrading mamba https://github.com/mamba-org/mamba/issues/1826 but then run into other issues.

**Comment by skanwal** [comment]
Other reported issues on Sonoma https://github.com/conda-forge/miniforge/issues/512

Might need to remove mamba from the instructions.

**Comment by skanwal** [comment]
Fixed with https://github.com/umccr/cwl-novice-tutorial/pull/12
